// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package pdpi;

// Required WCMP group selection mode parsed from ActionProfile annotations.
message WcmpGroupMode {
  enum ActionSelectionMode {
    ACTION_SELECTION_MODE_UNSPECIFIED = 0;
    DEFAULT_MODE_DETERMINED_BY_ACTION_SELECTOR = 1;
    HASH = 2;
    RANDOM = 3;
  }

  enum SizeSemantics {
    SIZE_SEMANTICS_UNSPECIFIED = 0;
    DEFAULT_SIZE_DETERMINED_BY_ACTION_SELECTOR = 1;
    SUM_OF_WEIGHTS = 2;
    SUM_OF_MEMBERS = 3;
  }

  ActionSelectionMode action_selection_mode = 1;
  SizeSemantics size_semantics = 2;
  int64 member_multiplier = 3;
  int64 max_member_weight = 4;
}
